Add required VORBISENC_LIBRARY for Linux builds
Fixes Link error CMakeFiles/resinstaller.dir/src/ogg_encode.cpp.o: undefined reference to symbol 'vorbis_encode_init_vbr'